# Set to true to add reviewers to PRs
addReviewers: true
addAssignees: author
reviewers:
  - octocat
  - bubkoo
  - clonejs
numberOfReviewers: 1
assignees:
  - bubkoo
  - octocat
numberOfAssignees: 0
skipKeywords:
  - wip
